language: cpp
compiler: g++
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq g++-4.8
 - export CXX="g++-4.8"
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
 - sudo apt-get install qt5-qmake
script:
 - qmake -project
 - qmake happygis.pro
 - make CXX=g++-4.8 LINK=g++-4.8
